name: Publish To Npm

on:
  push:
    branches: [publish-zion-ui]
jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish npm"

    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
      - name: Install modules
        run: pnpm install
      - name: Build
        run: cd packages/zion-ui-vite && npm run build
      - name: "Publish to the npm registry"
        # uses: primer/publish@3.0.0
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
          package: packages/zion-ui-vite